name: teno_rrule
description: Dart Recurrence Rule library that implements RFC5545 (iCalendar), support timezone (TZDateTime), week start (WKST), exclusion (EXDATES),...
version: 0.0.8
repository: https://github.com/hnvcam/teno_rrule

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  teno_datetime: ^1.0.8
  timezone: ^0.10.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0
